canonical/pipelines-rocks

viewer-crd-controller/rockcraft.yaml

Adding the `viewer-crd-controller rockcraft.yaml`.
1. Build the rock
```
rockcraft pack -v
```
3. Import the rock into a local docker registry
```
sudo skopeo --insecure-policy copy oci-archive:<name of the rock file>.rock docker-daemon:<img name>:0.1
```
4. Run the container image
```
docker run --rm <img name>:0.1
```
In this case we can say the output is okay, the error should go away in runtime when we pass the right arguments to the command and provide the right environment.
```
$ docker run --rm viewer:0.1
2023-05-11T12:29:13.051Z [pebble] Started daemon.
2023-05-11T12:29:13.057Z [pebble] POST /v1/services 5.057004ms 202
2023-05-11T12:29:13.057Z [pebble] Started default services with change 1.
2023-05-11T12:29:13.065Z [pebble] Service "controller" starting: controller …
```

feat: add viewer-crd-controller rockcraft.yaml

---

persistenceagent/rockcraft.yaml

Some minor adjustments are required since last time this ROCK was implementd. See comments below.
- Enabled new run-user.
- Removed old non-root user setup.
- Updated security team requirements part with proper options.

feat: persistenceagent rock integration

---

api-server/tox.ini
frontend/tox.ini
persistenceagent/tox.ini
scheduledworkflow/tox.ini
viewer-crd-controller/tox.ini
visualisation-server/tox.ini

Integration tests are described in the spec. To implement those tox.ini for each ROCK has integraton test environment.
Main items:
- Build rock
- Upload it to microk8s cache
- Checkout charm's repo
- Updated metadata.yaml to point to local ROCK
- Execute charm's integration tests
- 
Refer to spec for more details.
- Added tox.ini files to pipeline rocks. Integration tests env is setup.

feat: pipeline rocks integration tests

---

.github/workflows/issues_to_jira.yaml

Adding this automation will automatically create a Jira ticket for every PR that is opened in this repository.

ci: add automation for GH issues to duplicate in Jira

---

.github/workflows/build_and_scan_rocks.yaml

CVE scanning for ROCKs should be enabled on weekly schedule. The design is described in related spec.
Main design points:
- Automated workflow triggered on schedule.
- Each ROCK in the list of completed ROCKs is built (this brings in updated base image either ubuntu 20.04, 22.04 or bare), scanned for CVEs.
- Each CVE report is sent to Jira, where via automation a Jira ticket created for analysis and scheduling.
- Reports (tarball of JSONs) are uploaded as artefacts.
- Enable CVE scanning for pipeline ROCKs. Only frontend is not enabled, because it requires fixes to rockcraft.yaml.

feat: cve scanning in rocks

---

api-server/rockcraft.yaml

As part of ROCK integration it was discovered that it is more reliable to wait for all configuration to be availble before starting workload with `apiserver` ROCK. The solution is to disable startup in `rockcraft.yaml`
- Set startup of the ROCK to be disabled to ensure that workload only started by the charm when all information and configuration is ready, i.e. when all relations are established. This is required in order to prevent workload from slow recovery and to ensure faster startup.

fix: set startup to be disabled

---

frontend/rockcraft.yaml

Updating `frontend` ROCK to use proper command in order for service to start.
All other related patching has been done, i.e. version update to 2.0.0.
- Updated ROCK to use proper command.

Kf 4328 fix patch frontend

---

.github/workflows/integrate.yaml

This sets `fail-fast: false` so that integration CI failing for one rock does not block integration tests for another.  This is needed because, as is, a change to RockA will trigger RockB-RockX's CI, and if any RockB-RockX's CI fails it will cancel the CI of RockA.  This makes it hard to see if the current PR's changes are having an effect.

refactor: disable `fail-fast` in integration CI

---

frontend/rockcraft.yaml

Changes:
* bump source from 2.0.0 to 2.0.3
* change `base` to use `@` instead of `:` per new rockcraft syntax
* update version nomenclature to use `-` instead of `_` per new rockcraft requirements
Rock builds locally, but the CI is blocked until #52 is fixed.

chore: bump frontend from 2.0.0 (ckf-1.7) to 2.0.3 (ckf-1.8)

---

api-server/rockcraft.yaml

Changes:
* bump source version from 2.0.0-alpha.7 to 2.0.3
* update version to use '-' instead of '_', as per new rockcraft requirements
* rename base to ubuntu@20.04 as per new rockcraft syntax
* refactor compiler to use python3.7 like upstream and to incorporate changes in the upstream Dockerfile
* update server to use changes in upstream Dockerfile
closes #45

bump apiserver rock to ckf-1.8 (kfp 2.0.3)

---

.github/workflows/on_pull_request.yaml
.github/workflows/on_push.yaml

Update CI to use strict confinement for Microk8s. Follow up to https://github.com/canonical/pipelines-rocks/pull/55.

fix(ci): Use strict confinement for Microk8s

---

visualisation-server/rockcraft.yaml
visualisation-server/tox.ini

Follow up PR to #53
- update version according to canonical/bundle-kubeflow#747
- refactor tox.ini according to canonical/oidc-authservice-rock#14 and canonical/bundle-kubeflow#763
Note that I added place holders in place of sanity since there are none at the moment in order for the CI to not fail and be able to publish the produced ROCK after merging this. ~~I kept bundle integration tests in integration tests although this may sound too much to run for each ROCK.~~
ROCK can be built and unit goes to active using it. I didn't run any hands-on tests since this is really time consuming and I intend to run the bundle integration and manual tests once all kfp ROCKs are updated.
Update: bundle-integration tests fail in the CI due to https://github.com/canonical/pipelines-rocks/issues/61. …

chore: update visualization-server version and tox.ini file

---

frontend/rockcraft.yaml
frontend/tox.ini

Follow up PR to #51
- update version according to canonical/bundle-kubeflow#747
- refactor tox.ini according to canonical/oidc-authservice-rock#14 and canonical/bundle-kubeflow#763
- fix https://github.com/canonical/kfp-operators/issues/337
- add comment about `command`
- use placeholder instead of bundle-integration tests due to #61 (there are no charm integration tests for this charm)
- add placeholder instead of sanity tests since there are none at the moment  
Note CI needs a `sanity` and `integration environment in order to not fail and be able to publish the produced ROCK after merging this.
ROCK can be built and unit goes to active using it, after updating its command according to ROCK. I didn't run any hands-on tests since this is really time consuming and I intend to run the …

fix: update frontend version and tox.ini file

---

persistenceagent/rockcraft.yaml
persistenceagent/tox.ini

- bump source version from `2.0.0-alpha.7` to `2.0.3`
- update according to canonical/bundle-kubeflow#747
- rename base to ubuntu@20.04 as per new `rockcraft` syntax
- use `1.20/stable` snap for Go
- refactor `tox.ini` according to canonical/oidc-authservice-rock#14 and canonical/bundle-kubeflow#763
- use placeholder instead of integration tests (they fail for the same reasons as https://github.com/canonical/kfp-operators/issues/377)
- add placeholder instead of sanity tests since there are none at the moment
Note CI needs a `sanity` and `integration` environment in order to not fail and be able to publish the produced ROCK after merging this.
ROCK can be built and unit goes to active using it. I didn't run any hands-on tests since bundle-integration and manual tests will be run once all …

bump persistenceagent rock to ckf-1.8 (kfp 2.0.3)

---

viewer-crd-controller/rockcraft.yaml
viewer-crd-controller/tox.ini

- bump source version from `2.0.0-alpha.7` to `2.0.3`
- update according to canonical/bundle-kubeflow#747
- rename base to ubuntu@20.04 as per new `rockcraft` syntax
- use `1.20/stable` snap for Go
- refactor `tox.ini` according to canonical/oidc-authservice-rock#14 and canonical/bundle-kubeflow#763
- use placeholder instead of bundle-integration tests due to #61 (there are no charm integration tests for this charm)
- add placeholder instead of sanity tests since there are none at the moment
Note CI needs a `sanity` and `integration` environment in order to not fail and be able to publish the produced ROCK after merging this.
ROCK can be built and unit goes to active using it. I didn't run any hands-on tests since bundle-integration and manual tests will be run once all kfp ROCKs are …

bump viewer-crd-controller rock to ckf-1.8 (kfp 2.0.3)

---

scheduledworkflow/rockcraft.yaml
scheduledworkflow/tox.ini

- bump source version from `2.0.0-alpha.7` to `2.0.3`
- update according to canonical/bundle-kubeflow#747
- rename base to ubuntu@20.04 as per new `rockcraft` syntax
- use `1.20/stable` snap for Go
- refactor `tox.ini` according to canonical/oidc-authservice-rock#14 and canonical/bundle-kubeflow#763
- use placeholder instead of bundle-integration tests due to #61 (there are no charm integration tests for this charm)
- add placeholder instead of sanity tests since there are none at the moment
Note CI needs a `sanity` and `integration` environment in order to not fail and be able to publish the produced ROCK after merging this.
ROCK can be built and unit goes to active using it. I didn't run any hands-on tests since bundle-integration and manual tests will be run once all kfp ROCKs are …

bump scheduledworkflow rock to ckf-1.8 (kfp 2.0.3)  

---

persistenceagent/rockcraft.yaml

This should be merged after https://github.com/canonical/pipelines-rocks/pull/72.
Ref #69

chore: bump persistenceagent to 2.0.5

---

visualization-server/rockcraft.yaml

This should be merged after https://github.com/canonical/pipelines-rocks/pull/72.
Ref #69

chore: bump visualization-server to 2.0.5

---

api-server/rockcraft.yaml

This should be merged after https://github.com/canonical/pipelines-rocks/pull/72.
Ref #69

chore: bump api-server to 2.0.5

---

persistenceagent/rockcraft.yaml
persistenceagent/tests/test_rock.py
persistenceagent/tox.ini

closes: https://github.com/canonical/pipelines-rocks/issues/84
I have compared this file https://github.com/kubeflow/pipelines/blob/2.0.5/backend/Dockerfile.persistenceagent for tags [2.0.5](https://github.com/kubeflow/pipelines/blob/2.0.5/backend/Dockerfile.persistenceagent) and [2.2.0](https://github.com/kubeflow/pipelines/blob/2.2.0/backend/Dockerfile.persistenceagent). Changes: 
- Go bump 
- new env variables
Other changes:
- rewritten  the `rockcraft.yaml` based on up to date process 
- added tests for sanity
For experiment I tried to run the integration test for the rock but the bundle test is [failing to build charms](https://github.com/canonical/pipelines-rocks/actions/runs/9269011939/job/25501498014#step:9:562).

Update persistenceagent to 2.2.0

---

scheduledworkflow/rockcraft.yaml
scheduledworkflow/tests/test_rock.py
scheduledworkflow/tox.ini

closes: https://github.com/canonical/pipelines-rocks/issues/85
I have compared this file  https://github.com/kubeflow/pipelines/blob/2.0.5/backend/Dockerfile.scheduledworkflow for tags [2.0.5](https://github.com/kubeflow/pipelines/blob/2.0.5/backend/Dockerfile.scheduledworkflow) and [2.2.0](https://github.com/kubeflow/pipelines/blob/2.2.0/backend/Dockerfile.scheduledworkflow). Changes: 
- Go bump 
- new env variables
Other changes:
- rewritten  the `rockcraft.yaml` based on up to date process 
- added tests for sanity
For experiment I tried to run the integration test for the rock but the bundle test is [failing to build charms](https://github.com/canonical/pipelines-rocks/actions/runs/9269011939/job/25501498014#step:9:562).

Update scheduledworkflow to 2.2.0

---

viewer-crd-controller/rockcraft.yaml
viewer-crd-controller/tests/test_rock.py
viewer-crd-controller/tox.ini

closes: https://github.com/canonical/pipelines-rocks/issues/86
I have compared this file  https://github.com/kubeflow/pipelines/blob/2.0.5/backend/Dockerfile.viewercontroller
for tags [2.0.5](https://github.com/kubeflow/pipelines/blob/2.0.5/backend/Dockerfile.viewercontroller) and [2.2.0](https://github.com/kubeflow/pipelines/blob/2.2.0/backend/Dockerfile.viewercontroller). Changes: 
- Go bump 
Other changes:
- rewritten  the `rockcraft.yaml` based on up to date process (I changed the way we build it plus I added two envs which we were skipping so far)
- added tests for sanity
For experiment I tried to run the integration test for the rock but the bundle test is [failing to build charms](https://github.com/canonical/pipelines-rocks/actions/runs/9269011939/job/25501498014#step:9:562).

Update viewer-crd-controller to 2.2.0

---

visualization-server/rockcraft.yaml
visualization-server/tests/test_rock.py
visualization-server/tox.ini

Closes: https://github.com/canonical/pipelines-rocks/issues/87
I have compared tags `2.0.5` and `2.2.0` for this file https://github.com/kubeflow/pipelines/blob/2.2.0/backend/Dockerfile.visualization and there were no changes. 
Changes:
- I have cleaned up the structure of the `rockcraft.yaml` to be the same as in other ROCKs. 
- I have changed the base os to 22.04 (because of this there are some changes as 3.8 is not default python)
- I have added security team requirement 
- I have added sanity tests 
**Note:** when you build the ROCK and and run it locally with docker the server does not have any output. The only way to test if the rock is really working is to ssh to running rock and inspect the  processes (you can also just ssh to running ROCK and try to rrun it again from inside, if …

Update visualisation server to v2.2.0

---

metadata-writer/rockcraft.yaml

Closes: https://github.com/canonical/pipelines-rocks/issues/83
I have compared tags `2.0.5` and `2.2.0` for this file https://github.com/kubeflow/pipelines/blob/2.2.0/backend/metadata_writer/Dockerfile and there were no changes. 
Changes:
- I have cleaned up the structure of the `rockcraft.yaml` to be the same as in other ROCKs.

Update metadata writer to v2.2.0

---

api-server/rockcraft.yaml

Changes: I also did some refactoring based on #93.
Closes #82

chore: update api-server to 2.2.0

---

visualization-server/rockcraft.yaml

Closes: https://github.com/canonical/pipelines-rocks/issues/140
No changes in code the Docker image did not change 
https://github.com/kubeflow/pipelines/blob/2.2.0/backend/Dockerfile.visualization
https://github.com/kubeflow/pipelines/blob/2.3.0/backend/Dockerfile.visualization
I have bumped the tags.
**Steps for local comparison test**
```
rockcraft clean && rockcraft pack --verbosity=trace
sudo rockcraft.skopeo --insecure-policy copy oci-archive:visualization-server_2.3.0_amd64.rock docker-daemon:visualization-server:2.3.0
docker run gcr.io/ml-pipeline/visualization-server:2.3.0
########################################################
docker run visualization-server:2.3.0
2024-11-14T09:50:45.048Z [pebble] Started daemon.
2024-11-14T09:50:45.082Z [pebble] POST /v1/services 16.662624ms …
```

Upgrade visualisation server ROCK to 2.3.0

---

metadata-writer/rockcraft.yaml

closes #93 
There were no changes in the upstream image or dependencies from `2.2.0` to `2.3.0`, see the dir for both versions:
https://github.com/kubeflow/pipelines/tree/2.2.0/backend/metadata_writer
https://github.com/kubeflow/pipelines/tree/2.3.0/backend/metadata_writer

chore: upgrade metadata-writer Rock to 2.3.0

---

api-server/rockcraft.yaml
api-server/tests/test_rock.py
api-server/tox.ini

Closes #135 
* upgrades Rock version to `2.3.0`, changes from [Dockerfile](https://github.com/kubeflow/pipelines/blob/2.3.0/backend/Dockerfile):
* bump python version to `3.8`
*  bump `ARGO_VERSION` to `v3.4.17`
* adds sanity tests to the rockcraft project
1. Download the Rock artifact from the PR Checks [Summary](https://github.com/canonical/pipelines-rocks/actions/runs/11896323458)
2. Import the rock into your local docker registry using `skopeo`:
```
rockcraft.skopeo --insecure-policy copy oci-archive:api-server docker-daemon:api-server:test-rock
```
3. Run the Rock with the service command
```
LOG_LEVEL=info
docker run api-server:test-rock exec /bin/apiserver --config=/config --sampleconfig=/config/sample_config.json -logtostderr=true --logLevel=$LOG_LEVEL
```
4. Run the upstream …

chore: upgrade `api-server` Rock to 2.3.0

---

launcher/rockcraft.yaml
launcher/tests/test_rock.py
launcher/tox.ini

---
* Add rockcraft.yaml
* Add tests
* Add tox.ini
This is re-open request for #110.
---
Using [kfp-operators](https://github.com/canonical/kfp-operators). Modified [kfp-api/config.yaml](https://github.com/canonical/kfp-operators/blob/main/charms/kfp-api/config.yaml). Replaced "gcr.io/ml-pipeline/kfp-launcher@sha256:bef55a344574a25c557256d7c66cb19edacfd2008d694e5b6bb5b612d59feae0" with "vyurchenko581/kfp-launcher:2.2.0". 
Additionally, the default port for KUBEFLOW_LOCAL_HOST has been changed from 8080 to 8081 due to its unavailability on my local machine, as it is already in use.
Juju status after all tests passed:
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.5.4    unsupported  16:06:46+02:00 …
```

Added kubeflow pipelines launcher rock image

---

driver/rockcraft.yaml
driver/tests/test_rock.py
driver/tox.ini

---
* Add rockcraft.yaml
* Add tests
* Add tox.ini
This is re-open request for #109.
---
Using [kfp-operators](https://github.com/canonical/kfp-operators). Modified [kfp-api/config.yaml](https://github.com/canonical/kfp-operators/blob/main/charms/kfp-api/config.yaml). Replaced "gcr.io/ml-pipeline/kfp-driver" with "vyurchenko581/kfp-driver:2.2.0". 
Additionally, the default port for KUBEFLOW_LOCAL_HOST has been changed from 8080 to 8081 due to its unavailability on my local machine, as it is already in use.
Juju status after all tests passed:
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.5.4    unsupported  14:32:11+02:00
App                      Version                  Status  Scale  Charm …
```

Added kubeflow pipelines driver rock image

---

metadata-writer/rockcraft.yaml

Modify rock's service name to be the same with the one that the charm uses.
Ref #166

fix(metadata-writer): Use the same service name with charm

---

metadata-writer/rockcraft.yaml

Backport from #167
Modify rock's service name to be the same with the one that the charm uses.
Ref #166

fix(metadata-writer): Use the same service name with charm (#167)

---

viewer-crd-controller/rockcraft.yaml

Bump the rock 2.3.0 -> 2.4.0 in preparation for a new release.
The diff between the two Dockerfiles is:
```diff
< FROM golang:1.21.7-alpine3.19 as builder
---
> FROM golang:1.22.10-alpine3.21 as builder
20a21,28
>
> COPY ./go.mod ./
> COPY ./go.sum ./
> COPY ./hack/install-go-licenses.sh ./hack/
>
> RUN GO111MODULE=on go mod download
> RUN ./hack/install-go-licenses.sh
>
25d32
```
This only shows a bump in the golang version and changes in the go binary build command, which are already handled by the rock's go plugin.

chore: bump viewer 2.3.0 -> 2.4.0

---

persistenceagent/rockcraft.yaml

Closes: https://warthogs.atlassian.net/browse/KF-6819
Changes and reasoning:
- Go version bump
To test:
```
rockcraft clean && rockcraft pack --verbosity=trace --debug
sudo rockcraft.skopeo --insecure-policy copy oci-archive:persistenceagent_2.4.0_amd64.rock docker-daemon:misohu/persistenceagent:2.4.0
docker run <image>
docker exec -ti <container> bash
python3 -u /kfp/metadata_writer/metadata_writer.py
2025-02-06T09:35:33.928Z [persistenceagent] W0206 09:35:33.928456      15 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2025-02-06T09:35:33.928Z [persistenceagent] W0206 09:35:33.928519      15 client_config.go:664] error creating inClusterConfig, falling back to default config: unable to load in-cluster …
```

feat: update persistenceagent rock to 2.4.0

---

metadata-writer/rockcraft.yaml

Closes: https://warthogs.atlassian.net/browse/KF-6814
Compared with upstream changes https://www.diffchecker.com/Bn0XdYlk/
Changes and reasoning:
- Python version change
To test:
```
rockcraft clean && rockcraft pack --verbosity=trace --debug
sudo rockcraft.skopeo --insecure-policy copy oci-archive:metadata-writer_2.4.0_amd64.rock docker-daemon:misohu/metadata-writer:2.4.0
docker run <image>
docker exec -ti <container> bash
python3 -u /kfp/metadata_writer/metadata_writer.py
Traceback (most recent call last):
File "/kfp/metadata_writer/metadata_writer.py", line 39, in <module>
kubernetes.config.load_incluster_config()
File "/usr/local/lib/python3.9/dist-packages/kubernetes/config/incluster_config.py", line 118, in load_incluster_config
InClusterConfigLoader(
File …
```

feat: update metadata-writer rock to 2.4.0

---

driver/rockcraft.yaml

Coparison 2.2.0 to 2.4.0 https://www.diffchecker.com/oocOlcuJ/
Changes
- go version plus the extra build arg
- removed appuser (based on other rocks)

feat: update `kfp driver` to version 2.4.0

---

scheduledworkflow/rockcraft.yaml
scheduledworkflow/tests/test_rock.py

This commit upgrades the scheduledworkflow rock in preparation for a new release.
Fixes #184
This PR is based on the differences between both versions of the upstream Dockerfile:
```diff
21d20
24d22
33,38d30
< RUN go-licenses check ./backend/src/crd/controller/scheduledworkflow
< RUN go-licenses csv ./backend/src/crd/controller/scheduledworkflow > /tmp/licenses.csv && \
<     diff /tmp/licenses.csv backend/third_party_licenses/swf.csv && \
<     go-licenses save ./backend/src/crd/controller/scheduledworkflow --save_path /tmp/NOTICES
50,53d41
< COPY --from=builder …
```

chore: upgrade scheduledworkflow 2.4.0 -> 2.4.1

---

launcher/rockcraft.yaml
launcher/tests/test_rock.py

This commit upgrades the launcher rock in preparation for a new release.
Fixes #180
Changes based on the differences between both versions of the upstream Dockerfiles:
```diff
21d20
24d22
30,36d27
< RUN go-licenses check ./backend/src/v2/cmd/launcher-v2
< RUN go-licenses csv ./backend/src/v2/cmd/launcher-v2 > /tmp/licenses.csv && \
<     diff /tmp/licenses.csv backend/third_party_licenses/launcher.csv && \
<     go-licenses save ./backend/src/v2/cmd/launcher-v2 --save_path /tmp/NOTICES
<
45,47d35
< COPY --from=builder /tmp/licenses.csv /third_party/licenses.csv
< COPY …
```

chore: upgrade launcher 2.4.0 -> 2.4.1

---

frontend/rockcraft.yaml

This commit upgrades the frontend rock in preparation for a new release.
Fixes #179
No changes in upstream Dockerfiles, just tag.

chore: upgrade frontend 2.4.0 -> 2.4.1

---

persistenceagent/rockcraft.yaml
persistenceagent/tests/test_rock.py

This commit upgrades the persitenceagent rock in preparation for a new release.
Fixes #183
Changes based on the differences between the two versions of the upstream Dockerfile:
```diff
21d20
24d22
33,38d30
< RUN go-licenses check ./backend/src/agent/persistence
< RUN go-licenses csv ./backend/src/agent/persistence > /tmp/licenses.csv && \
<     diff /tmp/licenses.csv backend/third_party_licenses/persistence_agent.csv && \
<     go-licenses save ./backend/src/agent/persistence --save_path /tmp/NOTICES
48,51d39
< COPY --from=builder /tmp/licenses.csv /third_party/licenses.csv
< …
```

chore: upgrade persistenceagent 2.4.0 -> 2.4.1

---

driver/rockcraft.yaml
driver/tests/test_rock.py

This commit upgrades the driver rock in preparation for a new release.
These changes are based on the differences between the Dockerfile v2.4.0 and 2.4.1:
```diff
23d22
26d24
32,38d29
< RUN go-licenses check ./backend/src/v2/cmd/driver
< RUN go-licenses csv ./backend/src/v2/cmd/driver > /tmp/licenses.csv && \
<     diff /tmp/licenses.csv backend/third_party_licenses/driver.csv && \
<     go-licenses save ./backend/src/v2/cmd/driver --save_path /tmp/NOTICES
<
47,49d37
< COPY --from=builder /tmp/licenses.csv /third_party/licenses.csv
< COPY --from=builder /tmp/NOTICES …
```

chore: upgrade driver 2.4.0 -> 2.4.1

---

api-server/rockcraft.yaml

This commit upgrades the api-server rock in preparation for a new release.
Fixes #177
Changes based on the differences between the two versions of the upstream Dockerfiles:
```diff
22d21
25d23
29,34d26
< RUN go-licenses check ./backend/src/apiserver
< RUN go-licenses csv ./backend/src/apiserver > /tmp/licenses.csv && \
<   diff /tmp/licenses.csv backend/third_party_licenses/apiserver.csv && \
<   go-licenses save ./backend/src/apiserver --save_path /tmp/NOTICES
76,78d67
< COPY --from=builder /tmp/licenses.csv /third_party/licenses.csv
< COPY --from=builder /tmp/NOTICES …
```

chore: upgrade api-server 2.4.0 -> 2.4.1

---

visualization-server/rockcraft.yaml

This commit upgrades the visualization-server rock in preparation for a new release.
There are no major changes between the two versions, just the tag.
Fixes #186

chore: upgrade visualization-server 2.3.0 -> 2.4.1

---

.github/workflows/on_pull_request.yaml
.github/workflows/on_workflow_dispatch.yaml
api-server/rock-ci-metadata.yaml

Closes: https://github.com/canonical/pipelines-rocks/issues/200
This pr: 
- introduces `rock-ci-metadata.yaml` file for rock integration.
- add `workflow_dispatch` job for manual rock integration.
For full file creation steps please refer to [this](https://github.com/canonical/pipelines-rocks/issues/200#issuecomment-3112245114) comment.

feat: `api-server` create rocks-automation-ci.yaml

---

frontend/rock-ci-metadata.yaml

Closes: https://github.com/canonical/pipelines-rocks/issues/202
This pr: 
- introduces `rock-ci-metadata.yaml` file for rock integration.
**note:** `workflow_dispatch` is already part of repo
For full file creation steps please refer to [this](https://github.com/canonical/pipelines-rocks/issues/200#issuecomment-3112245114) comment.
Issue related to service file https://github.com/canonical/kfp-operators/issues/755

feat: `frontend` create rocks-automation-ci.yaml
