canonical/pipelines-rocks

scheduledworkflow/rockcraft.yaml
This PR is fix for this [pr](https://github.com/canonical/kfp-operators)
ustream dockerfile: https://github.com/kubeflow/pipelines/blob/2.0.0-alpha.7/backend/Dockerfile.scheduledworkflow
=> KF-1750 scheduledworkflow rock

visualisation-server/rockcraft.yaml
=> KF-2249 Visualisation Server Rock

scheduledworkflow/rockcraft.yaml
Some minor adjustments are required since last time this ROCK was implementd. See comments below.
- Added new non-root user setup.
- Removed old non-root user setup.
- Updated security requirements part to run with proper option.
=> feat: scheduledworkflow rock integration

visualisation-server/rockcraft.yaml
Some minor adjustments are required since last time this ROCK was implementd. See comments below.
- Added new non-root user setup.
- Updated service command.
- Removed old non-root user setup.
=> feat: visualisation-server rock integration

viewer-crd-controller/rockcraft.yaml
Some minor adjustments are required since last time this ROCK was implementd. See comments below.
- Updated version.
- Added ne non-root user setup.
- Removed old non-root user setup.
- Updated security requirement to use proper option.
=> feat: viewer-crd-controller rock integration

visualisation-server/rockcraft.yaml
https://github.com/canonical/pipelines-rocks/issues/29
- Fixed syntax error introduced by another PR.
=> fix: syntax error

scheduledworkflow/rockcraft.yaml
=> fix: scheduled workflow namespace environment variable

metadata-writer/rockcraft.yaml
=> chore: bump metadata-writer to 2.0.5

scheduledworkflow/rockcraft.yaml
=> chore: bump scheduledworkflow to 2.0.5

.github/workflows/build_and_scan_rocks.yaml, .github/workflows/on_pull_request.yaml, .github/workflows/on_push.yaml, README.md, frontend/rockcraft.yaml
=> chore: fix rocks terminology

viewer-crd-controller/rockcraft.yaml
Closes: https://github.com/canonical/pipelines-rocks/issues/139
No changes in code the Docker image did not change 
https://github.com/kubeflow/pipelines/blob/2.3.0/backend/Dockerfile.viewercontroller
https://github.com/kubeflow/pipelines/blob/2.2.0/backend/Dockerfile.viewercontroller
I have bumped the tags.
=> Upgrade viewer-crd-controller ROCK to 2.3.0

scheduledworkflow/rockcraft.yaml
=> feat: bump kfp-schedwf rock version and source code tag 2.2.0 -> 2.3.0

persistenceagent/rockcraft.yaml
=> feat: bump kfp-persistenceagent rock version and source code tag 2.2.0 -> 2.3.0

frontend/rockcraft.yaml
=> chore: upgrade `frontend` rock to 2.3.0

launcher/rockcraft.yaml
Coparison 2.2.0 to 2.4.0 https://www.diffchecker.com/iXJ6q2Dm/
Changes
- go version
- removed appuser (based on other rocks)
=> feat: update `kfp launcher` for version 2.4.0

visualization-server/rock-ci-metadata.yaml
Closes: https://github.com/canonical/pipelines-rocks/issues/209
This pr: 
- introduces `rock-ci-metadata.yaml` file for rock integration.
**note:** `workflow_dispatch` is already part of repo
For full file creation steps please refer to [this](https://github.com/canonical/pipelines-rocks/issues/200#issuecomment-3112245114) comment.
=> feat: `visualization-server` create rocks-automation-ci.yaml

viewer-crd-controller/rock-ci-metadata.yaml
Closes https://github.com/canonical/pipelines-rocks/issues/208
=> feat: add rock-ci-metadata.yaml for viewer

frontend/rock-ci-metadata.yaml
Closes: https://github.com/canonical/pipelines-rocks/issues/246
=> feat: frontend use user and command setting from service-config

metadata-writer/rock-ci-metadata.yaml
Closes: https://github.com/canonical/pipelines-rocks/issues/243
=> feat: kfp-metadata-writer use user setting from service-config

scheduledworkflow/rock-ci-metadata.yaml
Closes: https://github.com/canonical/pipelines-rocks/issues/245
=> feat: kfp-schedwf use user setting from service-config

api-server/rock-ci-metadata.yaml
Closes: https://github.com/canonical/pipelines-rocks/issues/242
=> feat: kfp-api use user setting from service-config

visualization-server/rock-ci-metadata.yaml
Closes: https://github.com/canonical/pipelines-rocks/issues/248
=> feat: visualuzation-server use user setting from service-config
